# Site settings
title: "redpixel.dk"
email: rp@redixel.dk
description: "Opinions, musings and other sophistry from an atheist, leftist, Danish/Swedish software engineer with a background in computer science."
baseurl: ""
url: "http://localhost"
title_description: "<p>Opinions, musings and other sophistry from an atheist, leftist, Danish/Swedish software engineer with a background in computer science. I may also talk about fun projects that I work on from time to time, or anime or games or whatever.</p>
<p>This page exists as a public place to air my thoughts and talk about fun things without some of the filters that are imposed by social media, my anxiety, and the knowledge that posts may be pushed to large parts of a \"friends list\". My identity is not a secret as such, merely slightly obscured to give me some peace of mind as I sometimes write about very personal things, and (very rarely) things that anger me to such an extent as to require copious amounts of swearing. The point being, you choosing to follow my activity here is mostly on <i>you</i>. And that allows me to be less nervous about what I write and how.</p>
<p>I will sometimes write in Danish, sometimes Swedish, sometimes English. It depends on context. If you'd like a post translated, or have questions or comments, I can be reached by mail via \"rp\" at this domain.</p>
<p>Comments may be enabled in the future, but this will require some work, so as to both allow anonymity and encourage thoughtful responses. But I do not expect this to be a frequently visited place anyway.</p>
<p>Redpixel was the hostname of a peculiar (and kind of shitty) laptop I owned long ago. It was powered by a Transmeta Crusoe processor, and the display featured a dead pixel, stuck in a very prominent red colour. When the display failed entirely, the laptop was stripped down to the motherboard and used as an at-home server. It is no longer in service, but its legacy lives on as a domain name.</p>"
# title_image: "data/redpixel.png"
# google_analytics: "UA-20365477-4"
# disqus_account: cartenoire
# github_repository: https://github.com/jacobtomlinson/carte-noire
# addthis_id: ra-513c6fa83da6ec67
post_limit: 5

timezone: Europe/Stockholm

# Social usernames/URLs
# twitter_username: _jacobtomlinson
# github_username:  jacobtomlinson
# instagram_username:
# reddit_username:
# linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
# xing_link:
# facebook_link:

# Footer
footer_left: "Based on <a href=\"https://github.com/jacobtomlinson/carte-noire\">carte-noire</a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
